daemon: fix init script and add --pidfile option
Signed-off-by: Corentin Chary <cchary@commonit.com>

diff --git a/debian/sockslink.init b/debian/sockslink.init
--- a/debian/sockslink.init
+++ b/debian/sockslink.init
@@ -5,9 +5,14 @@ DAEMON=/usr/sbin/sockslinkd
 NAME=sockslinkd
 DESC=sockslinkd
 
+. /lib/lsb/init-functions
+
 test -x $DAEMON || exit 0
 
-test ! -z "$DAEMON_NOT_CONFIGURED" || echo "$DESC is not yet configured, please edit /etc/default/sockslink."; exit 0
+if [ -n "${DAEMON_NOT_CONFIGURED}" -a "x${DAEMON_NOT_CONFIGURED}" != "x0" ]; then
+	echo "$DESC is not yet configured, please edit /etc/default/sockslink."
+	exit 0
+fi
 
 LOGDIR=/var/log/sockslink
 PIDFILE=/var/run/$NAME.pid
@@ -20,8 +25,6 @@ DODTIME=2                   # Time to wait for the server to die, in seconds
 if [ -f /etc/default/sockslink ] ; then
 	. /etc/default/sockslink
 fi
-
-set -e
 
 running_pid()
 {
@@ -45,7 +48,7 @@ running()
     [ ! -f "$PIDFILE" ] && return 1
     # Obtain the pid and check it against the binary name
     pid=`cat $PIDFILE`
-    running_pid $pid $NAME || return 1
+    running_pid $pid $DAEMON || return 1
     return 0
 }
 
@@ -60,7 +63,8 @@ force_stop() {
             kill -9 $pid
             [ -n "$DODTIME" ] && sleep "$DODTIME"s
             if running ; then
-                echo "Cannot kill $LABEL (pid=$pid)!"
+                log_failure_msg "Cannot kill $LABEL (pid=$pid)!"
+		log_end_msg 1
                 exit 1
             fi
         fi
@@ -71,59 +75,71 @@ force_stop() {
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
+	log_daemon_msg "Starting $DESC"
+
+	if running; then
+		log_failure_msg "(already running)"
+		log_end_msg 1
+		exit 0
+	fi
+
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
 		--exec $DAEMON -- $DAEMON_OPTS
-        if running ; then
-            echo "$NAME."
-        else
-            echo " ERROR."
-        fi
+	RC=$?
+	log_end_msg $RC
 	;;
   stop)
-	echo -n "Stopping $DESC: "
+	log_daemon_msg "Stopping $DESC"
 	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
 		--exec $DAEMON
-	echo "$NAME."
+	RC=$?
+	if [ $RC -eq 1 ]; then
+		rm -f $PIDFILE
+		log_failure_msg "(not running)"
+		log_end_msg $RC
+	elif [ $RC -eq 2 ]; then
+		log_failure_msg "(failed to stop)"
+		log_end_msg $RC
+	else
+		rm -f $PIDFILE
+		log_end_msg 0
+	fi
 	;;
   force-stop)
-	echo -n "Forcefully stopping $DESC: "
+	log_daemon_msg "Forcefully stopping $DESC"
         force_stop
-        if ! running ; then
-            echo "$NAME."
-        else
-            echo " ERROR."
-        fi
+	log_end_msg $?
 	;;
   reload)
-	echo "Reloading $DESC configuration files."
+	log_daemon_msg "Reloading $DESC helpers files."
 	start-stop-daemon --stop --signal 1 --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON
-  ;;
+		$PIDFILE --exec $DAEMON
+	log_end_msg $?
+	;;
   force-reload)
 	start-stop-daemon --stop --test --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON \
+		$PIDFILE --exec $DAEMON \
 	&& $0 restart \
 	|| exit 0
 	;;
   restart)
-    echo -n "Restarting $DESC: "
+    log_daemon_msg "Restarting $DESC"
 	start-stop-daemon --stop --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON
+		$PIDFILE --exec $DAEMON
 	[ -n "$DODTIME" ] && sleep $DODTIME
 	start-stop-daemon --start --quiet --pidfile \
-		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
-	echo "$NAME."
+		$PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+	log_end_msg $?
 	;;
   status)
-    echo -n "$LABEL is "
-    if running ;  then
-        echo "running"
-    else
-        echo " not running."
-        exit 1
-    fi
-    ;;
+        echo -n "$DESC is "
+	if running ;  then
+		echo "running (`cat $PIDFILE`)"
+	else
+		echo "not running."
+		exit 1
+	fi
+	;;
   *)
 	N=/etc/init.d/$NAME
 	echo "Usage: $N {start|stop|restart|reload|force-reload|status|force-stop}" >&2
